version: '3.9'
services:
  ecommerce-multi :
    build: .
    ports:
      - 8000:8000
    # develop:
    #   watch:
    #     - path: ./composer.json
    #       action: rebuild
    #     - path: ./paccomposerkage-lock.json
    #       action: rebuild
    #     - path: .
    #       target: /app
    #       action: sync
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - ecommerce_db
    networks:
      - ecommerce

  ecommerce_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - ecommerce

networks:
  ecommerce:

volumes:
  tasked: